import "./globals.css";
import HandTracking from "@/components/handDetector/handDetector";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <HandTracking />
      </body>
    </html>
  );
}
